# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-13 04:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='connections',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
