# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 01:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distance', '0003_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='msg_type',
            field=models.CharField(choices=[('FR', 'Friend Request'), ('NM', 'Normal Message')], default='NM', max_length=100),
        ),
    ]
