# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distance', '0005_auto_20170816_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='temp_unit',
            field=models.CharField(choices=[('K', 'Kelvin'), ('C', 'Celsius'), ('F', 'Fahrenheit')], default='K', max_length=100),
        ),
    ]
